### PR TITLE
Add dashed type for bar background

### PR DESCRIPTION
**Pull request by fcortezmaira**
Add the dashedBackground prop to dashed the bar background with two props:
- width: Define the dash width
- gap: Define the gap between dashs

### CODE REVIEW

**Comment by DarkKnight1992** [comment]
can you kindly publish this update on npm also ?

**Comment by markusl** [comment]
The latest version is now published.

**Comment by erolg** [comment]
related issue: #223 
@markusl @DarkKnight1992

**Comment by rajpootathar** [comment]
do we have dashed tint as well?

**Pull request merged**
